# This is a basic workflow to help you get started with Actions

name: Upload To Github Release
# uses: xresloader/upload-to-github-release@v1.5.0

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload-thesis-pdf:
    name: Upload built Tesis.pdf file to a new release
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1
        
      - name: Upload to GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: xresloader/upload-to-github-release@v1.5.0
        with:
          file: "build/Tesis.pdf"
          draft: true
